/* Generated By:JavaCC: Do not edit this line. PkgParserConstants.java */
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//		PARSER DE LOS PAQUETES DE FUNCIONES		//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package xfuzzy.lang;

public interface PkgParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int FORMAL_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int BINARY = 8;
  int UNARY = 9;
  int MF = 10;
  int DEFUZ = 11;
  int ALIAS = 12;
  int PARAM = 13;
  int DEFINED = 14;
  int EQUAL = 15;
  int GREATER = 16;
  int SMALLER = 17;
  int CENTER = 18;
  int BASIS = 19;
  int JAVA = 20;
  int ANSI_C = 21;
  int CPLUSPLUS = 22;
  int DERIVATIVE = 23;
  int REQUIRES = 24;
  int SOURCE = 25;
  int ID = 26;
  int OPERATOR = 27;
  int LBRACE = 28;
  int RBRACE = 29;
  int OTHER = 30;

  int DEFAULT = 0;
  int CODEBLOCK = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"binary\"",
    "\"unary\"",
    "\"mf\"",
    "\"defuz\"",
    "\"alias\"",
    "\"parameter\"",
    "\"definedfor\"",
    "\"equal\"",
    "\"greatereq\"",
    "\"smallereq\"",
    "\"center\"",
    "\"basis\"",
    "\"java\"",
    "\"ansi_c\"",
    "\"cplusplus\"",
    "\"derivative\"",
    "\"requires\"",
    "\"source\"",
    "<ID>",
    "<OPERATOR>",
    "\"{\"",
    "\"}\"",
    "<OTHER>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
  };

}
