/* Generated By:JavaCC: Do not edit this line. XflParserConstants.java */
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//		    PARSER DEL LENGUAJE XFL3			//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package xfuzzy.lang;

public interface XflParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int MULTI_LINE_COMMENT = 6;
  int IMPORT = 7;
  int OPERATORSET = 8;
  int TYPE = 9;
  int EXTENDS = 10;
  int RULEBASE = 11;
  int USING = 12;
  int IF = 13;
  int SYSTEM = 14;
  int AND = 15;
  int OR = 16;
  int NOT = 17;
  int VERY = 18;
  int MOREORLESS = 19;
  int SLIGHTLY = 20;
  int IS = 21;
  int ISNOT = 22;
  int GREATEROREQUAL = 23;
  int SMALLEROREQUAL = 24;
  int GREATER = 25;
  int SMALLER = 26;
  int APPROXEQUAL = 27;
  int VERYEQUAL = 28;
  int SLIGHTLYEQUAL = 29;
  int ASIGN = 30;
  int THEN = 31;
  int ID = 32;
  int OPERATOR = 33;
  int NUMBER = 34;
  int INTEGER = 35;
  int FLOAT = 36;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"import\"",
    "\"operatorset\"",
    "\"type\"",
    "\"extends\"",
    "\"rulebase\"",
    "\"using\"",
    "\"if\"",
    "\"system\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"+\"",
    "\"~\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"~=\"",
    "\"+=\"",
    "\"%=\"",
    "\"=\"",
    "\"->\"",
    "<ID>",
    "<OPERATOR>",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
  };

}
