//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Jfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg;

import xfuzzy.lang.*;

public class xfl_unary_sugeno extends Unary {
 public xfl_unary_sugeno() {
   super.parameter = new Parameter[1];
   super.parameter[0] = new Parameter("l");
   super.name = "sugeno";
   super.pkg = "xfl";
  }

 public double compute(double a) {
   double l = parameter[0].value;
 return (1-a)/(1+a*l); 
  }

 public double derivative(double a) {
   double deriv;
   double l = parameter[0].value;
 deriv = -(1+l)/((1+l*a)*(1+l*a)); 
   return deriv;
  }

 public boolean test () {
   double l = parameter[0].value;
   return ( l>-1 );
  }

 public String toJava(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "  double "+name+"(double a) {"+eol;
  code += "   double l = "+parameter[0].value+";"+eol;
   code += "    return (1-a)/(1+a*l); "+eol;
   code += "  }"+eol;
   return code;
  }

 public String toC(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "static double "+name+"(double a) {"+eol;
  code += " double l = "+parameter[0].value+";"+eol;
   code += "  return (1-a)/(1+a*l); "+eol;
   code += "}"+eol;
   return code;
  }

 public String toCpp(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "double "+name+"(double a) {"+eol;
  code += " double l = "+parameter[0].value+";"+eol;
   code += "  return (1-a)/(1+a*l); "+eol;
   code += "}"+eol+eol;
   return code;
  }
}
