//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Jfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg;

import xfuzzy.lang.*;

public class xfl_binary_mizumoto extends Binary {
 public xfl_binary_mizumoto() {
   super.parameter = new Parameter[0];
   super.name = "mizumoto";
   super.pkg = "xfl";
  }

 public double compute(double a, double b) {
 return 1-a+a*b; 
  }

 public double[] derivative(double a, double b) {
   double[] deriv = new double[2];
  deriv[0] = b-1;
  deriv[1] = a;
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String toJava(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "  double "+name+"(double a, double b) {"+eol;
   code += "    return 1-a+a*b; "+eol;
   code += "  }"+eol;
   return code;
  }

 public String toC(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "static double "+name+"(double a, double b) {"+eol;
   code += "  return 1-a+a*b; "+eol;
   code += "}"+eol;
   return code;
  }

 public String toCpp(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "double "+name+"(double a, double b) {"+eol;
   code += "  return 1-a+a*b; "+eol;
   code += "}"+eol;
   return code;
  }
}
