//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Jfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg;

import xfuzzy.lang.*;

public class xfl_binary_dienes_resher extends Binary {
 public xfl_binary_dienes_resher() {
   super.parameter = new Parameter[0];
   super.name = "dienes_resher";
   super.pkg = "xfl";
  }

 public double compute(double a, double b) {
 return (b>1-a? b : 1-a); 
  }

 public double[] derivative(double a, double b) {
   double[] deriv = new double[2];
  deriv[0] = (b<1-a? -1 : (b==(1-a) ? -0.5 : 0));
  deriv[1] = (b>1-a? 1 : (b==(1-a) ? 0.5 : 0));
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String toJava(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "  double "+name+"(double a, double b) {"+eol;
   code += "    return (b>1-a? b : 1-a); "+eol;
   code += "  }"+eol;
   return code;
  }

 public String toC(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "static double "+name+"(double a, double b) {"+eol;
   code += "  return (b>1-a? b : 1-a); "+eol;
   code += "}"+eol;
   return code;
  }

 public String toCpp(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "double "+name+"(double a, double b) {"+eol;
   code += "  return (b>1-a? b : 1-a); "+eol;
   code += "}"+eol;
   return code;
  }
}
