//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Jfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg;

import xfuzzy.lang.*;

public class xfl_binary_sum extends Binary {
 public xfl_binary_sum() {
   super.parameter = new Parameter[0];
   super.name = "sum";
   super.pkg = "xfl";
  }

 public double compute(double a, double b) {
 return a+b-a*b; 
  }

 public double[] derivative(double a, double b) {
   double[] deriv = new double[2];
  deriv[0] = 1-b;
  deriv[1] = 1-a;
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String toJava(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "  double "+name+"(double a, double b) {"+eol;
   code += "    return a+b-a*b; "+eol;
   code += "  }"+eol;
   return code;
  }

 public String toC(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "static double "+name+"(double a, double b) {"+eol;
   code += "  return a+b-a*b; "+eol;
   code += "}"+eol;
   return code;
  }

 public String toCpp(String name) {
   String eol = System.getProperty("line.separator", "\n");
   String code = "double "+name+"(double a, double b) {"+eol;
   code += "  return a+b-a*b; "+eol;
   code += "}"+eol;
   return code;
  }
}
