/* Generated By:JavaCC: Do not edit this line. XfuzzyConfigConstants.java */
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//   PARSER DE LA CONFIGURACION DE LAS DISTINTAS HERRAMIENTAS	//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package xfuzzy;

public interface XfuzzyConfigConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 3;
  int SINGLE_LINE_COMMENT2 = 4;
  int MULTI_LINE_COMMENT = 5;
  int TRAININGFILE = 6;
  int TESTFILE = 7;
  int LOGFILE = 8;
  int OUTPUTFILE = 9;
  int ALGORITHM = 10;
  int OPTION = 11;
  int ERRORFUNCTION = 12;
  int PREPROCESSING = 13;
  int POSTPROCESSING = 14;
  int ENDCONDITION = 15;
  int ENABLE = 16;
  int DISABLE = 17;
  int EOL = 18;
  int XFSIM_PLANT = 19;
  int XFSIM_INIT = 20;
  int XFSIM_LIMIT = 21;
  int XFSIM_LOG = 22;
  int XFSIM_PLOT = 23;
  int OTHER = 24;
  int CEOL = 25;
  int ID = 26;
  int FILE = 27;
  int PARAM = 28;
  int NUMBER = 29;
  int INTEGER = 30;
  int FLOAT = 31;
  int ERROR = 32;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"//\"",
    "\"#\"",
    "<MULTI_LINE_COMMENT>",
    "\"xfsl_training\"",
    "\"xfsl_test\"",
    "\"xfsl_log\"",
    "\"xfsl_output\"",
    "\"xfsl_algorithm\"",
    "\"xfsl_option\"",
    "\"xfsl_errorfunction\"",
    "\"xfsl_preprocessing\"",
    "\"xfsl_postprocessing\"",
    "\"xfsl_endcondition\"",
    "\"xfsl_enable\"",
    "\"xfsl_disable\"",
    "<EOL>",
    "\"xfsim_plant\"",
    "\"xfsim_init\"",
    "\"xfsim_limit\"",
    "\"xfsim_log\"",
    "\"xfsim_plot\"",
    "<OTHER>",
    "<CEOL>",
    "<ID>",
    "<FILE>",
    "<PARAM>",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "<ERROR>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
  };

}
